###define PBS arguments
#PBS -N estimate
#PBS -l nodes=node2:ppn=5,walltime=2400:00:00
#PBS -q high
#PBS -j oe
#PBS -o estimate_log

###job starting reminder
echo "Starting job at:"
date
hostname

###job dir
cd $PBS_O_WORKDIR

###job command

###compute split time

/root/anaconda3/bin/smc++ estimate 6.5e-9 -o ./  --polarization-error 0.5 ../*smc.gz

###job finished reminder
echo "Finished at:"
date
